version: '3'

services:
  mysql:
    image: mysql
    container_name: test_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
